# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f391f6ee15b85494683667509ca07eeecda7db853bd6b829efb29e91d53ec55c50a63de89cf0850b6979c73cfc64afbf9ef8c909148d5b696f7e06fa8e9b2d0

test:
  secret_key_base: 342ae174c392586e801090adfc910b886abff1be50ecd30ba8cd840e0c2c4ff06de648250b604b06216551293dd6b30332ef30f57d32de6e5b0fdf53706416b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
